defaults:
  - eqtl_catalogue

eqtl_catalogue_paths_imported: ???
eqtl_catalogue_study_index_out: ???
eqtl_catalogue_credible_sets_out: ???
mqtl_quantification_methods_blacklist: []
session:
  extended_spark_conf:
    "spark.sql.shuffle.partitions": "3200"
