defaults:
  - gwas_catalog_study_inclusion

catalog_study_files: ${datasets.gwas_catalog_studies}
catalog_ancestry_files: ${datasets.gwas_catalog_ancestries}
catalog_associations_file: ${datasets.gwas_catalog_associations}
variant_annotation_path: ${datasets.variant_annotation}
gwas_catalog_study_curation_file: ${datasets.gwas_catalog_study_curation}
harmonised_study_file: ${datasets.gwas_catalog_summary_stats_list}
criteria: ???
inclusion_list_path: ???
exclusion_list_path: ???
