defaults:
  - ld_index

ld_index_out: ${datasets.ld_index}
ld_matrix_template: ${datasets.ld_matrix_template}
ld_index_raw_template: ${datasets.ld_index_raw_template}
grch37_to_grch38_chain_path: ${datasets.chain_37_38}
liftover_ht_path: ${datasets.liftover_ht_path}
ld_populations:
  - afr # African-American
  - amr # American Admixed/Latino
  - asj # Ashkenazi Jewish
  - eas # East Asian
  - est # Estonian
  - fin # Finnish
  - nfe # Non-Finnish European
  - nwe # Northwestern European
  - seu # Southeastern European
# The version will of the gnomad will be inferred from ld_matrix_template and appended to the ld_index_out.
use_version_from_input: true
